"""
Django settings for hardwarelabs project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#-x@yyowc0rr@&yexw65r7d21i-m!%j!0zi(37)9a0ojitsn8i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # project apps
#    'techlab_systems',
#    'benchmarks',
#    'hardwarelabs_core',
#    'SSD',
#    'software_configuration',
#    'hardware_configuration',
#    'manufacturer',
    # third-party apps
    'guardian',
    'bulk_admin',
    'crispy_forms',
    # django contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Remote user auth
    'hardwarelabs_core.middleware.remote_user_attributes_middleware.RemoteUserAttrMiddleware',
]

ROOT_URLCONF = 'hardwarelabs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hardwarelabs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'hardwarelabs',
        'USER': 'admin',
        'PASSWORD': 'hardwareteam',
        'HOST': 'localhost',
        'PORT': '',
    },
    'old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

AUTHENTICATION_BACKENDS = {
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.RemoteUserBackend',
}

ADFS_GROUPS = [
    'procurement-rd',
    'hardware-labs',
    'techlab-admins',
    'openlab-admin',
]

ADFS_TO_DJANGO_GROUPS_MAPPING = {
    'procurement-rd': ['admin'],
    'hardware-labs': ['admin'],
    'techlab-admins': ['admin'],
    'openlab-admins': ['admin'],
    'cern-accounts-primary': ['view_techlab'],
}

ADFS_GROUPS_THAT_GIVE_STAFF_STATUS = [
    'procurement-rd',
]

ADFS_GROUPS_THAT_GIVE_SUPERUSER_STATUS = [
    'hardware-labs',
]

BASE_GROUP = 'all'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/www/hardwarelabs/backups'}

DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'admin',
        'PASSWORD': 'hardwareteam',
        'HOST': 'localhost'
    }
}
