# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpu', models.BooleanField(default=False, verbose_name='builds cpus?')),
                ('ssd', models.BooleanField(default=False, verbose_name='builds ssds?')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
    ]
