# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Architecture',
                'verbose_name_plural': 'Architectures',
            },
        ),
        migrations.CreateModel(
            name='ByteOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endianness', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'byte orders',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nb_cores', models.IntegerField(blank=True, null=True, verbose_name='number of cores')),
                ('cpu_mhz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='frequency (MHz)')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='techlab_systems.Architecture')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
            },
        ),
        migrations.CreateModel(
            name='HardwareConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('architecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_families', to='techlab_systems.Architecture')),
            ],
            options={
                'verbose_name': 'Hardware configuration',
                'verbose_name_plural': 'Hardware configurations',
                'permissions': set([('view_bench', 'View benchmarks for this hardware')]),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD manufacturer',
                'verbose_name_plural': 'SSD manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hardware_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='techlab_systems.HardwareConfiguration')),
            ],
            options={
                'ordering': ('hostname',),
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Operating system',
                'verbose_name_plural': 'Operating systems',
            },
        ),
        migrations.CreateModel(
            name='SoftwareConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techlab_systems.OS')),
            ],
            options={
                'verbose_name': 'Software configuration',
                'verbose_name_plural': 'Software configurations',
            },
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='capacity (GB)')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('endurance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='endurance (DWPD)')),
            ],
            options={
                'ordering': ['manufacturer', 'series', 'capacity'],
                'verbose_name': 'SSD',
                'verbose_name_plural': 'SSDs',
            },
        ),
        migrations.CreateModel(
            name='SSDController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD controller',
                'verbose_name_plural': 'SSD controllers',
            },
        ),
        migrations.CreateModel(
            name='SSDFlashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD flash type',
                'verbose_name_plural': 'SSD flash types',
            },
        ),
        migrations.CreateModel(
            name='SSDFormFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD form factor',
                'verbose_name_plural': 'SSD form factors',
            },
        ),
        migrations.CreateModel(
            name='SSDInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD interface',
                'verbose_name_plural': 'SSD interfaces',
            },
        ),
        migrations.CreateModel(
            name='SSDProcessSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='size (nm)')),
            ],
            options={
                'verbose_name': 'SSD process size',
                'verbose_name_plural': 'SSD process sizes',
            },
        ),
        migrations.CreateModel(
            name='SSDSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssd_series', to='techlab_systems.Manufacturer')),
            ],
            options={
                'verbose_name': 'SSD series',
                'verbose_name_plural': 'SSD series',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_configurations', to='techlab_systems.HardwareConfiguration')),
                ('software_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_configurations', to='techlab_systems.SoftwareConfiguration')),
            ],
            options={
                'verbose_name': 'System configurations',
                'verbose_name_plural': 'System configurations',
            },
        ),
        migrations.AddField(
            model_name='ssd',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='techlab_systems.SSDController'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='flash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='techlab_systems.SSDFlashType', verbose_name='flash type'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='form_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='techlab_systems.SSDFormFactor', verbose_name='form factor'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='techlab_systems.SSDInterface'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='techlab_systems.Manufacturer'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='process_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='techlab_systems.SSDProcessSize', verbose_name='process size'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='techlab_systems.SSDSeries'),
        ),
        migrations.AddField(
            model_name='node',
            name='software_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='techlab_systems.SoftwareConfiguration'),
        ),
        migrations.AddField(
            model_name='alias',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='techlab_systems.Node'),
        ),
    ]
