# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techlab_systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='architecture',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
    ]
