# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='capacity (GB)')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('endurance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='endurance (DWPD)')),
            ],
            options={
                'ordering': ['manufacturer', 'series', 'capacity'],
                'verbose_name': 'SSD',
                'verbose_name_plural': 'SSDs',
            },
        ),
        migrations.CreateModel(
            name='SSDController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD controller',
                'verbose_name_plural': 'SSD controllers',
            },
        ),
        migrations.CreateModel(
            name='SSDFlashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD flash type',
                'verbose_name_plural': 'SSD flash types',
            },
        ),
        migrations.CreateModel(
            name='SSDFormFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD form factor',
                'verbose_name_plural': 'SSD form factors',
            },
        ),
        migrations.CreateModel(
            name='SSDInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SSD interface',
                'verbose_name_plural': 'SSD interfaces',
            },
        ),
        migrations.CreateModel(
            name='SSDProcessSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='size (nm)')),
            ],
            options={
                'verbose_name': 'SSD process size',
                'verbose_name_plural': 'SSD process sizes',
            },
        ),
        migrations.CreateModel(
            name='SSDSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssd_series', to='manufacturer.Manufacturer')),
            ],
            options={
                'verbose_name': 'SSD series',
                'verbose_name_plural': 'SSD series',
            },
        ),
        migrations.AddField(
            model_name='ssd',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='SSD.SSDController'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='flash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='SSD.SSDFlashType', verbose_name='flash type'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='form_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='SSD.SSDFormFactor', verbose_name='form factor'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='SSD.SSDInterface'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='manufacturer.Manufacturer'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='process_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='SSD.SSDProcessSize', verbose_name='process size'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='SSD.SSDSeries'),
        ),
    ]
