# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssd',
            options={'ordering': ['manufacturer', 'series', 'capacity'], 'permissions': set([('view_bench', 'View benchmarks for this hardware')]), 'verbose_name': 'SSD', 'verbose_name_plural': 'SSDs'},
        ),
    ]
