# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Architecture',
                'verbose_name_plural': 'Architectures',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='model name')),
                ('nb_cores', models.IntegerField(verbose_name='number of cores')),
                ('base_frequency', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='base frequency (GHz)')),
                ('max_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='max frequency (GHz)')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='hardware_configuration.Architecture')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='manufacturer.Manufacturer')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
            },
        ),
    ]
